### ISSUE TITLE
This looks great!

### ISSUE THREAD

**Issue by ghost** [dbolkensteyn/vatic-js#1]
Hi I just tried this tool and its amazing!
I have another project https://www.eraseimage.com/ which does superpixel segmentation in JS.
One of the big advantage of this project is that it implement a nice annotation UI using Fabric.js.
You can adopt this for Vatic https://github.com/AKSHAYUBHAT/ImageSegmentation

**Comment by dbolkensteyn** [comment]
Thanks @AKSHAYUBHAT - I've just made a quick test of your project and it's indeed very convenient to really quickly segment images. It would perfect if it could also handle videos :)

I'll keep this in mind next time I'm working on this project. And indeed I'm really not a GUI expert :)
