### ISSUE TITLE
Can I just use it for offline?

### ISSUE THREAD

**Issue by lisaring** [dbolkensteyn/vatic-js#4]
when I download this JS tool for video annotation, many problems occured. we cannot use this tool offline,right?

**Comment by amtagrwl** [comment]
Have you set up a local server?

**Comment by Hack-NLP** [comment]
@lisaring .. in streamsaver.js there is a dependency from github...
so logically this one setting up offline is not possible.

**Comment by plusk01** [comment]
@lisaring I removed the `StreamSaver.js` dependency in [this](https://github.com/plusk01/vatic.js/commit/b893d60599a8cb7fb5bfa70108b05b735fbbcd2e#diff-7a9076d6d94e62c13d641aa71f19ae8eR474) commit of my fork.
