### ISSUE TITLE
Working offline? 

### ISSUE THREAD

**Issue by amtagrwl** [dbolkensteyn/vatic-js#6]
I am able to run add bounding boxes and then have optical flow track them through the video when I use [https://dbolkensteyn.github.io/vatic.js/](https://dbolkensteyn.github.io/vatic.js/). Although, when I use a local version downloaded on my computer, I can only read the frames and add bounding boxes, but the video doesn't play, neither does the tracking work. The video only plays when I remove/hide all the bounding boxes. I need the tool to work offline and locally for the data that I will be using it for. 

I suspect I missed something that's needed to set it up to work offline. Any support would be highly appreciated.

**Comment by amtagrwl** [comment]
The server wasnt set up properly. My bad. Its working now. Thanks for this amazing tool!

**Comment by 23pointsNorth** [comment]
Sorry can you please elaborate on what setup is needed for the server? I am having the same issues.
